export enum ThemeActions {
  SET_LIGHT_THEME = 'THEME_SET_LIGHT_THEME',
  SET_DARK_THEME = 'THEME_SET_DARK_THEME',
  RESET_THEME = 'THEME_RESET_THEME',
  SET_CUSTOM_THEME = 'THEME_SET_CUSTOM_THEME',
}
