import { NavLink } from 'react-router-dom';
export declare const drawerWidth = 250;
export declare const activeLinkClass = "active-link";
export declare const DrawerMenuContainer: import("styled-components").StyledComponent<"div", import("styled-components").DefaultTheme, {}, never>;
export declare const CloseDrawerContainer: import("styled-components").StyledComponent<"div", import("styled-components").DefaultTheme, {}, never>;
export declare const MenuListItem: import("styled-components").StyledComponent<any, import("styled-components").DefaultTheme, object, string | number | symbol>;
export declare const DrawerNavLink: import("styled-components").StyledComponent<typeof NavLink, import("styled-components").DefaultTheme, {}, never>;
export declare const Footer: import("styled-components").StyledComponent<"div", import("styled-components").DefaultTheme, {}, never>;
export declare const FooterHeader: import("styled-components").StyledComponent<"div", import("styled-components").DefaultTheme, {}, never>;
export declare const Version: import("styled-components").StyledComponent<"p", import("styled-components").DefaultTheme, {}, never>;
